### ISSUE TITLE
Implement check mechanic

### ISSUE THREAD

**Issue by senbar** [SigmaProductions/sigmaChess#19]
chessBoard class should have method isChecked() which iterates through every piece on the board and invokes canAttack on kingPiece (first iterate for first king position; then for the second).

**Comment by senbar** [comment]
![thinking](https://i.imgur.com/xXtBhavr.png "thinking")

**Comment by szymekc** [comment]
lo kurwa no to ciezko bedzie

**Comment by ekierkad** [comment]
zrobione ;)
