### ISSUE TITLE
rozmnazajace pionki

### ISSUE THREAD

**Issue by senbar** [SigmaProductions/sigmaChess#26]
--------
--------
--------
--------
P-------
P-------
-PPPPPPP
PPPPPPPP

pionki sie rozmnazaja przy poruszaniu sie 2 ruchy z 0,1 na 0,2 a pozniej 0,2 na 0,3

**Comment by ekierkad** [comment]
from board import *

##test if piecePawn can move
##TODO add test for both factions

board= chessBoard()

board.PRINTBOARD()

piece= board.getPiece(0,1)
board.movePiece(piece,0,2)

board.PRINTBOARD()

piece= board.getPiece(0,2)
board.movePiece(piece,0,3)



board.PRINTBOARD()

**Comment by szymekc** [comment]
fajnie to spierdoliles

**Comment by szymekc** [comment]
btw czemu zamkles #24 ?

**Comment by senbar** [comment]
fixed
